import LegalPage from '../components/LegalPage'

export const metadata = {
  title: 'Privacy Policy | Reinstatement Cost Assessment Ltd',
  description:
    'How Reinstatement Cost Assessment Ltd collects, uses and protects personal information submitted through this website, in line with UK GDPR and the Data Protection Act 2018.',
  alternates: { canonical: '/privacy-policy' },
  robots: { index: true, follow: true },
}

const UPDATED = '22 September 2026'

const sections = [
  {
    heading: '1. Who we are',
    body: [
      'This Privacy Policy is issued by Reinstatement Cost Assessment Ltd ("we", "us", "our"), a company providing professional rebuild cost assessments for insurance purposes to property owners, landlords, managing agents and block managers in the United Kingdom.',
      {
        list: [
          'Reinstatement Cost Assessment Ltd',
          '17 Hanover Square, London, W1S 1BN, United Kingdom',
          'Company number: 17101918',
          'Email: joseph@reinstatementcostassessment.org',
        ],
      },
      'We are the data controller for the personal information described in this policy. Our ICO registration reference is [INFORMATION REQUIRED].',
    ],
  },
  {
    heading: '2. Personal information we collect',
    body: [
      'We only collect the information that this website actually asks for, or that is generated automatically by your use of the site. Depending on how you interact with us, this may include:',
      {
        list: [
          'Your full name',
          'Your email address',
          'Your telephone number',
          'The service you have selected or enquired about (for example a Desktop, On-Site, or 3-Year Reinstatement Cost Assessment)',
          'Any further details you choose to include in the free-text "Notes" field of our enquiry form, which may include a property address or other property details if you provide them',
          'Correspondence you send us by email or telephone in connection with an enquiry or instruction',
          'Standard technical information generated by your visit, such as IP address, browser and device type, and pages viewed, collected via our website analytics/advertising tag (see our Cookie Policy)',
        ],
      },
      'We do not currently include dedicated form fields for property address, postcode or payment details on this website. If you provide this information voluntarily (for example within the enquiry notes field, by email or by telephone), we process it in line with this policy.',
    ],
  },
  {
    heading: '3. How we use your information',
    body: [
      'We use personal information for the following purposes only:',
      {
        list: [
          'Responding to enquiries submitted through our contact form or sent to us by email or telephone',
          'Providing quotations and arranging Desktop or On-Site Reinstatement Cost Assessments',
          'Communicating with you about an existing or prospective instruction',
          'Preparing and delivering reinstatement cost assessment reports',
          'Maintaining business and accounting records',
          'Meeting our legal and regulatory obligations',
          'Keeping our website secure and functioning correctly',
          'Measuring the performance of our website and advertising, including Google Ads',
        ],
      },
      'We do not use your personal information for any purpose beyond those listed above, and we do not sell personal information to third parties.',
    ],
  },
  {
    heading: '4. Our lawful basis for processing',
    body: [
      'Under UK GDPR, we rely on the following lawful bases, depending on the specific processing activity:',
      {
        list: [
          'Contract — where processing is necessary to take steps at your request before entering into a contract with us, or to perform a contract for a reinstatement cost assessment you have instructed',
          'Legitimate interests — for responding to general enquiries, maintaining business records, and keeping our website secure, where this does not override your rights and interests',
          'Legitimate interests — for non-essential cookies and similar technologies, such as advertising and analytics tags, used to measure and improve our website and advertising (see our Cookie Policy)',
          'Legal obligation — where we are required to retain or disclose information to comply with the law, for example accounting and tax requirements',
        ],
      },
    ],
  },
  {
    heading: '5. Who we share information with',
    body: [
      'We do not sell or rent personal information. We may share limited personal information with the following categories of third party, strictly as necessary to operate our business and this website:',
      {
        list: [
          'Formspree, Inc. — the third-party form processing provider used to receive and deliver enquiries submitted through our contact form',
          'Our website hosting and infrastructure providers, who process data on our behalf to keep the website online and secure',
          'Google, for the purpose of measuring website and advertising performance (see our Cookie Policy for details of the Google services currently configured on this site)',
          'Our professional advisers (such as our accountant or solicitor), where reasonably necessary',
          'Regulators, law enforcement or other authorities, where we are legally required to disclose information',
        ],
      },
      'We do not currently use a separate CRM system or payment provider on this website. If this changes, we will update this policy accordingly.',
    ],
  },
  {
    heading: '6. Google services used on this website',
    body: [
      'This website uses a Google tag (implemented via Google’s gtag.js library) that is linked to a Google Ads account for conversion tracking, so that we can measure the effectiveness of our advertising. Depending on your cookie consent choices, this may involve Google setting cookies on your device and processing data such as your IP address and on-site activity for advertising measurement purposes.',
      'We have not identified a separate Google Analytics property or Google Tag Manager container configured in the website code at the time of writing. If our use of Google’s services changes, this section will be updated to reflect that.',
      'This website does not currently display a cookie consent banner, so the Google tag described above runs by default on every visit. You can control cookies through your browser settings — see our Cookie Policy for details.',
    ],
  },
  {
    heading: '7. How long we keep your information',
    body: [
      'We retain personal information only for as long as is reasonably necessary for the purposes set out in this policy, including to provide our services, maintain business and accounting records, and meet applicable legal, tax and regulatory obligations. Where information is no longer needed for these purposes, we take steps to delete or anonymise it. We do not currently operate a formal published retention schedule; if you would like more detail about how long a specific category of information is likely to be kept, please contact us using the details in Section 11.',
    ],
  },
  {
    heading: '8. Your rights',
    body: [
      'Subject to applicable conditions and exemptions under UK GDPR and the Data Protection Act 2018, you have the right to:',
      {
        list: [
          'Be informed about how we use your personal information (this policy)',
          'Request access to the personal information we hold about you',
          'Request that inaccurate personal information be corrected',
          'Request erasure of your personal information in certain circumstances',
          'Request that we restrict the processing of your personal information in certain circumstances',
          'Request a copy of certain personal information in a portable format, where applicable',
          'Object to certain types of processing, including processing based on legitimate interests',
          'Not be subject to decisions based solely on automated processing which produce legal or similarly significant effects, where applicable — we do not currently carry out any such automated decision-making',
          'Withdraw consent at any time, where our processing is based on consent, without affecting the lawfulness of processing before withdrawal',
        ],
      },
      'To exercise any of these rights, please contact us using the details in Section 11. We may need to verify your identity before responding.',
    ],
  },
  {
    heading: '9. Keeping your information secure',
    body: [
      'We take reasonable technical and organisational steps to protect personal information submitted to us against unauthorised access, loss, misuse or alteration. No method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee absolute security.',
    ],
  },
  {
    heading: '10. Complaints and the ICO',
    body: [
      'If you have a concern about how we handle your personal information, we would welcome the opportunity to address it directly — please see our Complaints Procedure or contact us using the details below.',
      'You also have the right to lodge a complaint with the UK’s independent regulator for data protection, the Information Commissioner’s Office (ICO), at https://ico.org.uk/. We are not currently able to confirm our ICO registration reference on this page — see Section 1.',
    ],
  },
  {
    heading: '11. Contact us',
    body: [
      'For any question about this Privacy Policy or how we handle your personal information, please contact:',
      {
        list: [
          'Reinstatement Cost Assessment Ltd',
          '17 Hanover Square, London, W1S 1BN, United Kingdom',
          'Email: joseph@reinstatementcostassessment.org',
        ],
      },
    ],
  },
  {
    heading: '12. Changes to this policy',
    body: [
      'We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. The "Last updated" date at the top of this page shows when it was last revised. We encourage you to review this page periodically.',
    ],
  },
]

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      pageName="Privacy Policy"
      eyebrow="Legal"
      title="Privacy Policy"
      updated={UPDATED}
      intro="This Privacy Policy explains how Reinstatement Cost Assessment Ltd collects, uses, shares and protects personal information in connection with this website and the reinstatement cost assessment services we provide."
      sections={sections}
    />
  )
}
